spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/itoken-personnel
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
thymeleaf:
  enabled: true
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8

  ##thymeleaf页面模板配置
  mvc:
    view:
      prefix: /
      suffix: .html