server:
  port: 8080

spring:
  profiles:
    active: prod
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/itoken-personnel?serverTimezone=CTT
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
##thymeleaf页面模板配置
  mvc:
    view:
      prefix: /
      suffix: .html

      mybatis:
        mapper-locations: classpath:mapper/*.xml   //mybatis的mapper文件所在路径
        type-aliases-package: com.itoken.personnel.entity   //实体类路径
